version: '3.8'

services:
  php:
    image: php:8.1-cli
    container_name: php-container
    volumes:
      - .:/var/www/html
    working_dir: /var/www/html
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
    networks:
      - app-network
    depends_on:
      - mysql
    links:
      - mysql
    command: bash -c "composer install && php"
    ports:
      - "8080:8080"
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: W5K&Byr&E-rD
      MYSQL_DATABASE: php_doctrine_test
      MYSQL_USER: user_test
      MYSQL_PASSWORD: W5K&Byr&E-rD
    networks:
      - app-network
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
